name: .NET

on:
  pull_request:
    branches: [ prod ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
      env:
        NUGET_AUTH_TOKEN: '%NUGET_AUTH_TOKEN%'

    - name: Restore dependencies
      run: dotnet restore LogRPush.sln

    - name: Build
      run: dotnet build LogRPush.sln --no-restore --configuration Release

    - name: Diagnostic
      run: echo dir *.* /s

    - name: Pack LogRPush
      run: dotnet pack --no-build --configuration Release ${{github.workspace}}/src/LogRPush/LogRPush.csproj --output .

    - name: Pack LogRWebMonitor
      run: dotnet pack --no-build --configuration Release ${{github.workspace}}/src/LogRWebMonitor/LogRWebMonitor.csproj --output .

    - name: Push Nuget
      run: dotnet nuget push *.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.nuget}} --skip-duplicate
