name: .NET

on:
  pull_request:
    branches: [ prod ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore LogRPush.sln
    - name: Build
      run: dotnet build LogRPush.sln --no-restore
    - name: Publish LogRPush to nuget
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: ${{github.workspace}}/src/LogRPush/LogRPush.csproj
        PACKAGE_NAME: LogRPush
        NUGET_SOURCE: https://api.nuget.org
        NUGET_KEY: ${{secrets.nuget}}
    - name: Publish LogRWebMonitor to nuget
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: ${{github.workspace}}/src/LogRWebMonitor/LogRWebMonitor.csproj
        PACKAGE_NAME: LogRWebMonitor
        NUGET_SOURCE: https://api.nuget.org
        NUGET_KEY: ${{secrets.nuget}}